name: BMW Autoplius Scraper

on:
  schedule:
    - cron: '*/30 * * * *'  # Darbojas ik pēc 30 minūtēm
  workflow_dispatch:      # Atļauj palaist manuāli

jobs:
  build:
    runs-on: ubuntu-latest
    # Dodam atļauju rakstīt failus atpakaļ repozitorijā
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 cloudscraper

      - name: Run bot
        run: python bot.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add seen_bmw.txt
          # Pievienojam nosacījumu, lai nemestu kļūdu, ja nav ko saglabāt
          git commit -m "Update seen ads [skip ci]" || exit 0
          git push
